### ISSUE TITLE
Excellent widget...one enhancement request

### ISSUE THREAD

**Issue by jagan999** [ltdangkhoa/Flutter-Speedometer#1]
Thanks for this simple and wonderful widget. I have one enhancement request. It would be great if we could specify multiple ranges rather than only one warning level. As an example, I could have a range 0-20 as red, 20-50 as green, 50-70 as orange, 70-100 as red again. Is this possible?

**Comment by ltdangkhoa** [comment]
> Thanks for this simple and wonderful widget. I have one enhancement request. It would be great if we could specify multiple ranges rather than only one warning level. As an example, I could have a range 0-20 as red, 20-50 as green, 50-70 as orange, 70-100 as red again. Is this possible?

Possible ;) but I have no spare time right now
